/**
 * Book Shelf API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AddBookToBookshelfDto {
  /**
   * Identifier of the book to add to the shelf.
   */
    bookId: string;
}

