/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdminUserViewDto { 
    id?: string;
    username?: string;
    email?: string;
    firstName?: string;
    lastName?: string;
    isActive?: boolean;
    isEmailVerified?: boolean;
    role?: string;
}

