/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {PageBookSummaryDto} from './pageBookSummaryDto';


export interface AuthorDetailsDto {
  id?: string;
  name?: string;
  summary?: string;
  imageUrl?: string;
  books?: PageBookSummaryDto;
}

