/**
 * Book Shelf API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {PagedResponseBookSummaryDto} from './pagedResponseBookSummaryDto';


export interface AuthorDetailsDto {
  /**
   * Unique author identifier.
   */
  id?: string;
  /**
   * Author\'s full name.
   */
  name?: string;
  /**
   * Short biography of the author.
   */
  summary?: string;
  /**
   * URL of the author\'s image; null when none is set.
   */
  imageUrl?: string;
  /**
   * A page of books written by the author.
   */
  books?: PagedResponseBookSummaryDto;
}

