/**
 * Book Shelf API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {PagedResponseBookSummaryDto} from './pagedResponseBookSummaryDto';


export interface BookshelfDetailsDto {
  /**
   * Unique shelf identifier.
   */
    id?: string;
  /**
   * Shelf name.
   */
    name?: string;
  /**
   * Shelf description.
   */
    description?: string;
  /**
   * A page of books contained in the shelf.
   */
  books?: PagedResponseBookSummaryDto;
}

