/**
 * Book Shelf API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {BookLanguageDto} from './bookLanguageDto';
import {BookAuthorDto} from './bookAuthorDto';
import {BookPublisherDto} from './bookPublisherDto';
import {BookGenreDto} from './bookGenreDto';


export interface BookDetailsDto {
  /**
   * Unique book identifier.
   */
    id?: string;
  /**
   * Book title.
   */
    title?: string;
  /**
   * International Standard Book Number.
   */
    isbn?: string;
  /**
   * Total number of pages.
   */
    pages?: number;
  /**
   * Year of publication.
   */
    yearPublished?: number;
  /**
   * Short synopsis of the book.
   */
    summary?: string;
  /**
   * Physical or digital format of the book.
   */
    format?: BookDetailsDto.FormatEnum;
  author?: BookAuthorDto;
  language?: BookLanguageDto;
  publisher?: BookPublisherDto;
  /**
   * Genres associated with the book.
   */
  genres?: Set<BookGenreDto>;
  /**
   * URL of the cover image; empty when none is set.
   */
    coverImageUrl?: string;
}
export namespace BookDetailsDto {
    export const FormatEnum = {
        Hardcover: 'HARDCOVER',
        Paperback: 'PAPERBACK',
        Digital: 'DIGITAL'
    } as const;
    export type FormatEnum = typeof FormatEnum[keyof typeof FormatEnum];
}


