/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuthorDto } from './authorDto';
import { LanguageDto } from './languageDto';
import { PublisherDto } from './publisherDto';
import { GenreDto } from './genreDto';


export interface BookDetailsDto { 
    id?: string;
    title?: string;
    isbn?: string;
    pages?: number;
    yearPublished?: number;
    summary?: string;
    format?: BookDetailsDto.FormatEnum;
    author?: AuthorDto;
    language?: LanguageDto;
    publisher?: PublisherDto;
    genres?: Set<GenreDto>;
    coverImageUrl?: string;
}
export namespace BookDetailsDto {
    export const FormatEnum = {
        Hardcover: 'HARDCOVER',
        Paperback: 'PAPERBACK',
        Digital: 'DIGITAL'
    } as const;
    export type FormatEnum = typeof FormatEnum[keyof typeof FormatEnum];
}


