/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {BookLanguageDto} from './bookLanguageDto';
import {BookAuthorDto} from './bookAuthorDto';
import {BookPublisherDto} from './bookPublisherDto';
import {BookGenreDto} from './bookGenreDto';


export interface BookDetailsDto {
    id?: string;
    title?: string;
    isbn?: string;
    pages?: number;
    yearPublished?: number;
    summary?: string;
    format?: BookDetailsDto.FormatEnum;
  author?: BookAuthorDto;
  language?: BookLanguageDto;
  publisher?: BookPublisherDto;
  genres?: Set<BookGenreDto>;
    coverImageUrl?: string;
}
export namespace BookDetailsDto {
    export const FormatEnum = {
        Hardcover: 'HARDCOVER',
        Paperback: 'PAPERBACK',
        Digital: 'DIGITAL'
    } as const;
    export type FormatEnum = typeof FormatEnum[keyof typeof FormatEnum];
}


