/**
 * Book Shelf API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BookshelfSummaryDto {
  /**
   * Unique shelf identifier.
   */
    id?: string;
  /**
   * Shelf name.
   */
    name?: string;
  /**
   * Number of books currently on the shelf.
   */
    bookCount?: number;
}

