/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageBookSummaryDto } from './pageBookSummaryDto';


export interface BookshelfDetailsDto { 
    id?: string;
    name?: string;
    description?: string;
    books?: PageBookSummaryDto;
}

