/**
 * Book Shelf API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GenreCreateDto {
  /**
   * Genre name; must be unique (case-insensitive).
   */
  name: string;
  /**
   * Short description of the genre.
   */
  description?: string;
}

