/**
 * Book Shelf API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GenreDto {
  /**
   * Unique genre identifier.
   */
    id?: string;
  /**
   * Genre name.
   */
    name?: string;
  /**
   * Short description of the genre.
   */
  description?: string;
}

