/**
 * Book Shelf API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {AuthorSummaryDto} from './authorSummaryDto';


export interface PagedResponseAuthorSummaryDto {
  content?: Array<AuthorSummaryDto>;
  pageNumber?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
  isLast?: boolean;
}

