/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BookSummaryDto } from './bookSummaryDto';


export interface PagedResponseBookSummaryDto { 
    content?: Array<BookSummaryDto>;
    pageNumber?: number;
    pageSize?: number;
    totalElements?: number;
    totalPages?: number;
    isLast?: boolean;
}

