/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminUserViewDto } from './adminUserViewDto';


export interface PagedResponseAdminUserViewDto { 
    content?: Array<AdminUserViewDto>;
    pageNumber?: number;
    pageSize?: number;
    totalElements?: number;
    totalPages?: number;
    isLast?: boolean;
}

