/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageableObject } from './pageableObject';
import { BookshelfSummaryDto } from './bookshelfSummaryDto';
import { SortObject } from './sortObject';


export interface PageBookshelfSummaryDto { 
    totalElements?: number;
    totalPages?: number;
    size?: number;
    content?: Array<BookshelfSummaryDto>;
    number?: number;
    sort?: SortObject;
    first?: boolean;
    last?: boolean;
    numberOfElements?: number;
    pageable?: PageableObject;
    empty?: boolean;
}

