/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PermissionRequestDto {
  permission: PermissionRequestDto.PermissionEnum;
  reason: string;
}

export namespace PermissionRequestDto {
  export const PermissionEnum = {
    ModerateReviews: 'MODERATE_REVIEWS'
  } as const;
  export type PermissionEnum = typeof PermissionEnum[keyof typeof PermissionEnum];
}


