/**
 * Book Shelf API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PermissionRequestDto {
  /**
   * Privilege to grant or revoke.
   */
  permission: PermissionRequestDto.PermissionEnum;
  /**
   * Administrative reason, recorded on the audit event.
   */
  reason: string;
}
export namespace PermissionRequestDto {
  export const PermissionEnum = {
    ModerateReviews: 'MODERATE_REVIEWS',
    ModerateBooks: 'MODERATE_BOOKS'
  } as const;
  export type PermissionEnum = typeof PermissionEnum[keyof typeof PermissionEnum];
}


