/**
 * Book Shelf API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReadingChallengeViewDto {
  id?: string;
  userId?: string;
  year?: number;
  goal?: number;
  booksRead?: number;
  completed?: boolean;
}

