/**
 * Book Shelf API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReviewUpdateDto {
  /**
   * Review title.
   */
    title: string;
  /**
   * Optional review body.
   */
    comment?: string;
  /**
   * Rating from 1 to 5.
   */
    rating?: number;
}

