/**
 * Book Shelf API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReviewViewDto {
  /**
   * Unique review identifier.
   */
    id?: string;
  /**
   * Review title.
   */
    title?: string;
  /**
   * Review body.
   */
    comment?: string;
  /**
   * Rating from 1 to 5.
   */
    rating?: number;
  /**
   * Identifier of the review\'s author.
   */
    userId?: string;
  /**
   * Display name of the review\'s author.
   */
    username?: string;
  /**
   * Identifier of the reviewed target entity.
   */
    targetId?: string;
  /**
   * Type of the reviewed target entity.
   */
    targetType?: string;
  /**
   * Timestamp when the review was created.
   */
    createdAt?: string;
  /**
   * Timestamp when the review was last updated.
   */
    updatedAt?: string;
}

