/**
 * Book Shelf API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserPermissionsDto {
  userId?: string;
  permissions?: Set<UserPermissionsDto.PermissionsEnum>;
}
export namespace UserPermissionsDto {
  export const PermissionsEnum = {
    ModerateReviews: 'MODERATE_REVIEWS',
    ModerateBooks: 'MODERATE_BOOKS'
  } as const;
  export type PermissionsEnum = typeof PermissionsEnum[keyof typeof PermissionsEnum];
}


