spring:
  application:
    name: book-shelf
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: validate
  data:
    web:
      pageable:
        max-page-size: 200
        default-page-size: 20
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

logging:
  pattern:
    console: "%d{HH:mm:ss} %-5p --- [%15.15t] %-40.40logger{39} : %m%n"
  file:
    name: logs/book-shelf.log
  logback:
    rollingpolicy:
      max-history: 7
      total-size-cap: 100MB
  level:
    root: INFO
    bg.softuni.bookshelf: INFO
    org.springframework: WARN

application:
  security:
    jwt:
      # This MUST be provided via an environment variable in production
      secret-key: ${JWT_SECRET_KEY}
      expiration: 86400000 # 24 hours
    auto-seed-admin: false
