package bg.softuni.bookshelf.config;

import io.swagger.v3.oas.models.Components;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.security.SecurityRequirement;
import io.swagger.v3.oas.models.security.SecurityScheme;
import org.springframework.boot.info.BuildProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.Optional;

/**
 * OpenAPI / Swagger UI configuration.
 * <p>
 * The API version is read from {@link BuildProperties} (generated by the Gradle
 * {@code springBoot { buildInfo() }} task from {@code project.version}), so the documented version
 * tracks {@code build.gradle} with no duplicated literal. The dependency is optional: when
 * {@code build-info.properties} is absent (for example an IDE run without the task), the version
 * falls back to {@code "unknown"} rather than failing startup.
 */
@Configuration
public class OpenApiConfig {

    private static final String BEARER_SCHEME_NAME = "bearerAuth";
    private static final String UNKNOWN_VERSION = "unknown";

    private final Optional<BuildProperties> buildProperties;

    public OpenApiConfig(Optional<BuildProperties> buildProperties) {
        this.buildProperties = buildProperties;
    }

    @Bean
    public OpenAPI bookShelfOpenAPI() {
        String version = buildProperties
                .map(BuildProperties::getVersion)
                .orElse(UNKNOWN_VERSION);

        return new OpenAPI()
                .info(new Info()
                        .title("Book Shelf API")
                        .version(version)
                        .description("REST API for the Book Shelf application."))
                .addSecurityItem(new SecurityRequirement()
                        .addList(BEARER_SCHEME_NAME))
                .components(new Components()
                        .addSecuritySchemes(BEARER_SCHEME_NAME,
                                new SecurityScheme()
                                        .name(BEARER_SCHEME_NAME)
                                        .type(SecurityScheme.Type.HTTP)
                                        .scheme("bearer")
                                        .bearerFormat("JWT")));
    }
}