export * from './adminAPI.service';
import { AdminAPIService } from './adminAPI.service';
export * from './adminModerationAPI.service';
import { AdminModerationAPIService } from './adminModerationAPI.service';
export * from './authenticationAPI.service';
import { AuthenticationAPIService } from './authenticationAPI.service';
export * from './bookAPI.service';
import { BookAPIService } from './bookAPI.service';
export * from './reviewAPI.service';
import { ReviewAPIService } from './reviewAPI.service';
export * from './userProfileAPI.service';
import { UserProfileAPIService } from './userProfileAPI.service';
export * from './userShelfAPI.service';
import { UserShelfAPIService } from './userShelfAPI.service';
export const APIS = [AdminAPIService, AdminModerationAPIService, AuthenticationAPIService, BookAPIService, ReviewAPIService, UserProfileAPIService, UserShelfAPIService];
