export * from './adminAPI.service';
import {AdminAPIService} from './adminAPI.service';
import {AdminAuthorAPIService} from './adminAuthorAPI.service';
import {AdminGenreAPIService} from './adminGenreAPI.service';
import {AdminLanguageAPIService} from './adminLanguageAPI.service';
import {AdminPublisherAPIService} from './adminPublisherAPI.service';
import {AuthenticationAPIService} from './authenticationAPI.service';
import {BookAPIService} from './bookAPI.service';
import {ModerationAPIService} from './moderationAPI.service';
import {ReadingChallengeAPIService} from './readingChallengeAPI.service';
import {ReviewAPIService} from './reviewAPI.service';
import {UserProfileAPIService} from './userProfileAPI.service';
import {UserShelfAPIService} from './userShelfAPI.service';

export * from './adminAuthorAPI.service';
export * from './adminGenreAPI.service';
export * from './adminLanguageAPI.service';
export * from './adminPublisherAPI.service';
export * from './authenticationAPI.service';
export * from './bookAPI.service';
export * from './moderationAPI.service';
export * from './readingChallengeAPI.service';
export * from './reviewAPI.service';
export * from './userProfileAPI.service';
export * from './userShelfAPI.service';
export const APIS = [AdminAPIService, AdminAuthorAPIService, AdminGenreAPIService, AdminLanguageAPIService, AdminPublisherAPIService, AuthenticationAPIService, BookAPIService, ModerationAPIService, ReadingChallengeAPIService, ReviewAPIService, UserProfileAPIService, UserShelfAPIService];
