/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import {Inject, Injectable, Optional} from '@angular/core';
import {HttpClient, HttpContext, HttpEvent, HttpResponse} from '@angular/common/http';
import {Observable} from 'rxjs';
import {OpenApiHttpParams, QueryParamStyle} from '../query.params';

// @ts-ignore
import {LogProgressDto} from '../model/logProgressDto';
// @ts-ignore
import {ProblemDetail} from '../model/problemDetail';
// @ts-ignore
import {ReadingChallengeCreateDto} from '../model/readingChallengeCreateDto';
// @ts-ignore
import {ReadingChallengeViewDto} from '../model/readingChallengeViewDto';

// @ts-ignore
import {BASE_PATH, COLLECTION_FORMATS} from '../variables';
import {Configuration} from '../configuration';
import {BaseService} from '../api.base.service';


@Injectable({
  providedIn: 'root'
})
export class ReadingChallengeAPIService extends BaseService {

  constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string | string[], @Optional() configuration?: Configuration) {
    super(basePath, configuration);
  }

  /**
   * Create a reading challenge
   * Creates a yearly reading challenge for the authenticated user.
   * @endpoint post /api/challenges
   * @param readingChallengeCreateDto
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public createChallenge(readingChallengeCreateDto: ReadingChallengeCreateDto, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<ReadingChallengeViewDto>;
  public createChallenge(readingChallengeCreateDto: ReadingChallengeCreateDto, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpResponse<ReadingChallengeViewDto>>;
  public createChallenge(readingChallengeCreateDto: ReadingChallengeCreateDto, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpEvent<ReadingChallengeViewDto>>;
  public createChallenge(readingChallengeCreateDto: ReadingChallengeCreateDto, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<any> {
    if (readingChallengeCreateDto === null || readingChallengeCreateDto === undefined) {
      throw new Error('Required parameter readingChallengeCreateDto was null or undefined when calling createChallenge.');
    }

    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      'application/json'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;


    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/challenges`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<ReadingChallengeViewDto>('post', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        body: readingChallengeCreateDto,
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? {transferCache: localVarTransferCache} : {}),
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Get a challenge by year
   * Retrieves the authenticated user\&#39;s challenge for a given year.
   * @endpoint get /api/challenges
   * @param year The challenge year
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public getChallenge(year: number, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<ReadingChallengeViewDto>;
  public getChallenge(year: number, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpResponse<ReadingChallengeViewDto>>;
  public getChallenge(year: number, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpEvent<ReadingChallengeViewDto>>;
  public getChallenge(year: number, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<any> {
    if (year === null || year === undefined) {
      throw new Error('Required parameter year was null or undefined when calling getChallenge.');
    }

    let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      'year',
      <any>year,
      QueryParamStyle.Form,
      true,
    );


    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      'application/json'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;


    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/challenges`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<ReadingChallengeViewDto>('get', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        params: localVarQueryParameters.toHttpParams(),
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? {transferCache: localVarTransferCache} : {}),
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Log reading progress
   * Adds progress to a challenge, completing it when the goal is reached.
   * @endpoint put /api/challenges/{challengeId}/progress
   * @param challengeId The UUID of the challenge
   * @param logProgressDto
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public logProgress(challengeId: string, logProgressDto: LogProgressDto, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<ReadingChallengeViewDto>;
  public logProgress(challengeId: string, logProgressDto: LogProgressDto, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpResponse<ReadingChallengeViewDto>>;
  public logProgress(challengeId: string, logProgressDto: LogProgressDto, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpEvent<ReadingChallengeViewDto>>;
  public logProgress(challengeId: string, logProgressDto: LogProgressDto, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<any> {
    if (challengeId === null || challengeId === undefined) {
      throw new Error('Required parameter challengeId was null or undefined when calling logProgress.');
    }
    if (logProgressDto === null || logProgressDto === undefined) {
      throw new Error('Required parameter logProgressDto was null or undefined when calling logProgress.');
    }

    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      'application/json'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;


    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/challenges/${this.configuration.encodeParam({
      name: "challengeId",
      value: challengeId,
      in: "path",
      style: "simple",
      explode: false,
      dataType: "string",
      dataFormat: "uuid"
    })}/progress`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<ReadingChallengeViewDto>('put', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        body: logProgressDto,
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? {transferCache: localVarTransferCache} : {}),
        reportProgress: reportProgress
      }
    );
  }

}
